// This file is auto-generated by `payload generate:importmap`.
import { VercelBlobClientUploadHandler as VercelBlobClientUploadHandler_0 } from '@payloadcms/storage-vercel-blob/client'

export const importMap = {
  '@payloadcms/storage-vercel-blob/client#VercelBlobClientUploadHandler': VercelBlobClientUploadHandler_0,
}
